version: "3.8"

services:
  app:
    build: ./
    depends_on:
      - db
    ports:
      - "5001:5001"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/
      MONGODB_DATABASE: task_database
      MONGODB_COLLECTION: tasks
  db:
    image: mongo:4.0-xenial # use a recent version of the official MongoDB image on Docker Hub
    container_name: mongodb
    ports:
      - "27018:27018" # map port 27017 of host machine to port 27017 of container